FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y openssh-server

# 这个我也不知道为什么，加了这一行确实能启动
RUN mkdir /var/run/sshd

# 设置 root 用户密码
RUN echo 'root:wangjin' | chpasswd

# 允许root用户通过SSH登录
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# 这个也不是我写的
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

# 公开端口
EXPOSE 22

# C++开发环境
RUN sudo apt install -y build-essential \
    && apt-get install -y cmake \
    && apt-get install -y llvm \
    && apt-get install -y clang \
    && apt-get install -y clang-format \
    && apt-get install -y clangd \
    && apt-get install -y gdb lldb

# 启动SSH服务
CMD ["/usr/sbin/sshd", "-D"]
